// *** DO NOT MODIFY ***
// AUTOGENERATED BY go generate

package dns

import (
	"net"
)

func (rr *A) pack(msg []byte, off int, compression map[string]int, compress bool) (int, error) {
	l := rr.Hdr.len()
	l += net.IPv4len // A
	return l, nil
}
func unpackA(msg []byte, off int) (*A, int, error) {
	l := 0
	l += net.IPv4len // A
	return nil, l, nil
}
func (rr *AAAA) pack(msg []byte, off int, compression map[string]int, compress bool) (int, error) {
	l := rr.Hdr.len()
	l += net.IPv6len // AAAA
	return l, nil
}
func unpackAAAA(msg []byte, off int) (*AAAA, int, error) {
	l := 0
	l += net.IPv6len // AAAA
	return nil, l, nil
}
