// *** DO NOT MODIFY ***
// AUTOGENERATED BY go generate

package dns

import (
	"encoding/base64"
	"net"
)

func (rr *A) pack() int {
	l := rr.Hdr.len()
	l += net.IPv4len // A
	return l
}
func (rr *A) unpack() int {
	l := rr.Hdr.len()
	l += net.IPv4len // A
	return l
}
func (rr *AAAA) pack() int {
	l := rr.Hdr.len()
	l += net.IPv6len // AAAA
	return l
}
func (rr *AAAA) unpack() int {
	l := rr.Hdr.len()
	l += net.IPv6len // AAAA
	return l
}
